# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='app.proto',
  package='launchpad',
  syntax='proto3',
  serialized_options=b'Z\010app/sync',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tapp.proto\x12\tlaunchpad\x1a\x1fgoogle/protobuf/timestamp.proto\"U\n\x13PortalAppDeployment\x12-\n\ttimestamp\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07\x61ppName\x18\x02 \x01(\tB\nZ\x08\x61pp/syncb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])




_PORTALAPPDEPLOYMENT = _descriptor.Descriptor(
  name='PortalAppDeployment',
  full_name='launchpad.PortalAppDeployment',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='launchpad.PortalAppDeployment.timestamp', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='appName', full_name='launchpad.PortalAppDeployment.appName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=142,
)

_PORTALAPPDEPLOYMENT.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
DESCRIPTOR.message_types_by_name['PortalAppDeployment'] = _PORTALAPPDEPLOYMENT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PortalAppDeployment = _reflection.GeneratedProtocolMessageType('PortalAppDeployment', (_message.Message,), {
  'DESCRIPTOR' : _PORTALAPPDEPLOYMENT,
  '__module__' : 'app_pb2'
  # @@protoc_insertion_point(class_scope:launchpad.PortalAppDeployment)
  })
_sym_db.RegisterMessage(PortalAppDeployment)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
